### ISSUE TITLE
Vault Generation Hung/Deadlocked

### ISSUE THREAD

**Issue by FoxFireX** [ImplementsLegend/VaultFaster#6]
Went into a three player co-op vault on latest pre-release (2.0.3.1), and when we entered the first real room, it hadn't finished loading. Getting closer didn't trigger any improvements, and we couldn't leave the first room because even the tunnels out hadn't finished generating. Feels like a deadlock or hung thread from my perspective. We attempted to shut down the server, but the shutdown itself seemed hung, so I killed the server. After logging back in, all three players were in the Overworld instead of the Vault (where we logged out), and were buried in the ground. (I switched us all to spectator so we could reposition back into air.)

The server had saved what we had done, so we decided to try again. Possibly of note, this was an crystal with an augment (geode caves), but nothing else. Next vault after restart seemed to be working better, we got to spread out and explore, but after several rooms the generation again appeared to be hung. This time it was an elixir vault, so we worked within the rooms that did generate and completed elixir, but due to lack of lodestones we had to exit through the portal. That worked alright. I then stopped the server to consider switching to a different version of the mod, and got this stacktrace. When the server was shut down, nobody was in a vault, so no generation should still have been ongoing, but it looks like something was still running.

java.lang.InterruptedException
[19:31:45] [Server thread/INFO] [ne.cr.ft.FTBBackups/]: Shutting down scheduler thread
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[19:31:45] [Server thread/INFO] [ne.cr.ft.or.qu.co.QuartzScheduler/]: Scheduler ftbbackups2_$_NON_CLUSTERED shutting down.
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[19:31:45] [Server thread/INFO] [ne.cr.ft.or.qu.co.QuartzScheduler/]: Scheduler ftbbackups2_$_NON_CLUSTERED paused.
	at TRANSFORMER/vaultfaster@2.0.3.1/implementslegend.mod.vaultfaster.SectionedTemplate.place(SectionedTemplate.kt:64)
[19:31:45] [Server thread/INFO] [ne.cr.ft.or.qu.co.QuartzScheduler/]: Scheduler ftbbackups2_$_NON_CLUSTERED shutdown complete.
	at TRANSFORMER/the_vault@1.18.2-3.15.1.3321/iskallia.vault.core.world.template.configured.ChunkedTemplate.place(ChunkedTemplate.java:524)
[19:31:45] [Server thread/INFO] [ne.cr.ft.FTBBackups/]: Shutting down the config watcher executor
	at TRANSFORMER/the_vault@1.18.2-3.15.1.3321/iskallia.vault.core.world.generator.GridGenerator.generate(GridGenerator.java:122)
[19:31:45] [Server thread/INFO] [ne.cr.ft.FTBBackups/]: Shutting down backup cleaning executor
	at TRANSFORMER/the_vault@1.18.2-3.15.1.3321/iskallia.vault.core.world.generator.VaultGenerator.lambda$initServer$0(VaultGenerator.java:19)
[19:31:45] [Server thread/INFO] [ne.cr.ft.FTBBackups/]: Shutting down backup executor
	at TRANSFORMER/the_vault@1.18.2-3.15.1.3321/iskallia.vault.core.event.Event.lambda$register$2(Event.java:73)
[19:31:45] [Server thread/INFO] [ne.cr.ft.FTBBackups/]: =========Checking everything is shut down============
	at TRANSFORMER/the_vault@1.18.2-3.15.1.3321/iskallia.vault.core.event.Event.lambda$invoke$0(Event.java:50)
[19:31:45] [Server thread/INFO] [ne.cr.ft.FTBBackups/]: Scheduler Shutdown:true
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[19:31:45] [Server thread/INFO] [ne.cr.ft.FTBBackups/]: Config watcher Shutdown:true
	at TRANSFORMER/the_vault@1.18.2-3.15.1.3321/iskallia.vault.core.event.Event.lambda$invoke$1(Event.java:48)
[19:31:45] [Server thread/INFO] [ne.cr.ft.FTBBackups/]: Cleaner watcher Shutdown:true
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[19:31:45] [Server thread/INFO] [ne.cr.ft.FTBBackups/]: Backup Executor Shutdown:true
	at TRANSFORMER/the_vault@1.18.2-3.15.1.3321/iskallia.vault.core.event.Event.invoke(Event.java:48)
[19:31:45] [Server thread/INFO] [ne.cr.ft.FTBBackups/]: ========Shutdown completed, FTB Backups has now finished shutting down==========
	at TRANSFORMER/the_vault@1.18.2-3.15.1.3321/iskallia.vault.core.event.common.SurfaceGenerationEvent.invoke(SurfaceGenerationEvent.java:27)
[19:31:45] [Thread-0/INFO] [Puzzles Lib/]: Reloading server config for pickupnotifier
	at TRANSFORMER/the_vault@1.18.2-3.15.1.3321/iskallia.vault.core.world.generator.DummyChunkGenerator.m_183621_(DummyChunkGenerator.java:73)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.chunk.ChunkStatus.m_156246_(ChunkStatus.java:116)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.chunk.ChunkStatus$SimpleGenerationTask.m_183270_(ChunkStatus.java:313)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.chunk.ChunkStatus.m_187788_(ChunkStatus.java:262)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ChunkMap.md7f1c4a$lambda$scheduleVaultChunkGeneration$4$2(ChunkMap.java:2853)
	at MC-BOOTSTRAP/datafixerupper@4.1.27/com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ChunkMap.md7f1c4a$lambda$scheduleVaultChunkGeneration$6$0(ChunkMap.java:2851)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
java.lang.InterruptedException
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at TRANSFORMER/vaultfaster@2.0.3.1/implementslegend.mod.vaultfaster.SectionedTemplate.place(SectionedTemplate.kt:64)
	at TRANSFORMER/the_vault@1.18.2-3.15.1.3321/iskallia.vault.core.world.template.configured.ChunkedTemplate.place(ChunkedTemplate.java:524)
	at TRANSFORMER/the_vault@1.18.2-3.15.1.3321/iskallia.vault.core.world.generator.GridGenerator.generate(GridGenerator.java:122)
	at TRANSFORMER/the_vault@1.18.2-3.15.1.3321/iskallia.vault.core.world.generator.VaultGenerator.lambda$initServer$0(VaultGenerator.java:19)
	at TRANSFORMER/the_vault@1.18.2-3.15.1.3321/iskallia.vault.core.event.Event.lambda$register$2(Event.java:73)
	at TRANSFORMER/the_vault@1.18.2-3.15.1.3321/iskallia.vault.core.event.Event.lambda$invoke$0(Event.java:50)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at TRANSFORMER/the_vault@1.18.2-3.15.1.3321/iskallia.vault.core.event.Event.lambda$invoke$1(Event.java:48)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at TRANSFORMER/the_vault@1.18.2-3.15.1.3321/iskallia.vault.core.event.Event.invoke(Event.java:48)
	at TRANSFORMER/the_vault@1.18.2-3.15.1.3321/iskallia.vault.core.event.common.SurfaceGenerationEvent.invoke(SurfaceGenerationEvent.java:27)
	at TRANSFORMER/the_vault@1.18.2-3.15.1.3321/iskallia.vault.core.world.generator.DummyChunkGenerator.m_183621_(DummyChunkGenerator.java:73)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.chunk.ChunkStatus.m_156246_(ChunkStatus.java:116)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.chunk.ChunkStatus$SimpleGenerationTask.m_183270_(ChunkStatus.java:313)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.chunk.ChunkStatus.m_187788_(ChunkStatus.java:262)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ChunkMap.md7f1c4a$lambda$scheduleVaultChunkGeneration$4$2(ChunkMap.java:2853)
	at MC-BOOTSTRAP/datafixerupper@4.1.27/com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ChunkMap.md7f1c4a$lambda$scheduleVaultChunkGeneration$6$0(ChunkMap.java:2851)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
java.lang.InterruptedException
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at TRANSFORMER/vaultfaster@2.0.3.1/implementslegend.mod.vaultfaster.SectionedTemplate.place(SectionedTemplate.kt:64)
	at TRANSFORMER/the_vault@1.18.2-3.15.1.3321/iskallia.vault.core.world.template.configured.ChunkedTemplate.place(ChunkedTemplate.java:524)
	at TRANSFORMER/the_vault@1.18.2-3.15.1.3321/iskallia.vault.core.world.generator.GridGenerator.generate(GridGenerator.java:122)
	at TRANSFORMER/the_vault@1.18.2-3.15.1.3321/iskallia.vault.core.world.generator.VaultGenerator.lambda$initServer$0(VaultGenerator.java:19)
	at TRANSFORMER/the_vault@1.18.2-3.15.1.3321/iskallia.vault.core.event.Event.lambda$register$2(Event.java:73)
	at TRANSFORMER/the_vault@1.18.2-3.15.1.3321/iskallia.vault.core.event.Event.lambda$invoke$0(Event.java:50)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at TRANSFORMER/the_vault@1.18.2-3.15.1.3321/iskallia.vault.core.event.Event.lambda$invoke$1(Event.java:48)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at TRANSFORMER/the_vault@1.18.2-3.15.1.3321/iskallia.vault.core.event.Event.invoke(Event.java:48)
	at TRANSFORMER/the_vault@1.18.2-3.15.1.3321/iskallia.vault.core.event.common.SurfaceGenerationEvent.invoke(SurfaceGenerationEvent.java:27)
	at TRANSFORMER/the_vault@1.18.2-3.15.1.3321/iskallia.vault.core.world.generator.DummyChunkGenerator.m_183621_(DummyChunkGenerator.java:73)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.chunk.ChunkStatus.m_156246_(ChunkStatus.java:116)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.chunk.ChunkStatus$SimpleGenerationTask.m_183270_(ChunkStatus.java:313)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.chunk.ChunkStatus.m_187788_(ChunkStatus.java:262)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ChunkMap.md7f1c4a$lambda$scheduleVaultChunkGeneration$4$2(ChunkMap.java:2853)
	at MC-BOOTSTRAP/datafixerupper@4.1.27/com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ChunkMap.md7f1c4a$lambda$scheduleVaultChunkGeneration$6$0(ChunkMap.java:2851)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool.helpJoin(ForkJoinPool.java:1883)
	at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:440)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:687)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:927)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at TRANSFORMER/vaultfaster@2.0.3.1/implementslegend.mod.vaultfaster.SectionedTemplate.generate$lambda$5(SectionedTemplate.kt:34)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
java.lang.InterruptedException
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at TRANSFORMER/vaultfaster@2.0.3.1/implementslegend.mod.vaultfaster.SectionedTemplate.place(SectionedTemplate.kt:64)
	at TRANSFORMER/the_vault@1.18.2-3.15.1.3321/iskallia.vault.core.world.template.configured.ChunkedTemplate.place(ChunkedTemplate.java:524)
	at TRANSFORMER/the_vault@1.18.2-3.15.1.3321/iskallia.vault.core.world.generator.GridGenerator.generate(GridGenerator.java:122)
	at TRANSFORMER/the_vault@1.18.2-3.15.1.3321/iskallia.vault.core.world.generator.VaultGenerator.lambda$initServer$0(VaultGenerator.java:19)
	at TRANSFORMER/the_vault@1.18.2-3.15.1.3321/iskallia.vault.core.event.Event.lambda$register$2(Event.java:73)
	at TRANSFORMER/the_vault@1.18.2-3.15.1.3321/iskallia.vault.core.event.Event.lambda$invoke$0(Event.java:50)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at TRANSFORMER/the_vault@1.18.2-3.15.1.3321/iskallia.vault.core.event.Event.lambda$invoke$1(Event.java:48)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at TRANSFORMER/the_vault@1.18.2-3.15.1.3321/iskallia.vault.core.event.Event.invoke(Event.java:48)
	at TRANSFORMER/the_vault@1.18.2-3.15.1.3321/iskallia.vault.core.event.common.SurfaceGenerationEvent.invoke(SurfaceGenerationEvent.java:27)
	at TRANSFORMER/the_vault@1.18.2-3.15.1.3321/iskallia.vault.core.world.generator.DummyChunkGenerator.m_183621_(DummyChunkGenerator.java:73)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.chunk.ChunkStatus.m_156246_(ChunkStatus.java:116)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.chunk.ChunkStatus$SimpleGenerationTask.m_183270_(ChunkStatus.java:313)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.chunk.ChunkStatus.m_187788_(ChunkStatus.java:262)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ChunkMap.md7f1c4a$lambda$scheduleVaultChunkGeneration$4$2(ChunkMap.java:2853)
	at MC-BOOTSTRAP/datafixerupper@4.1.27/com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ChunkMap.md7f1c4a$lambda$scheduleVaultChunkGeneration$6$0(ChunkMap.java:2851)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

**Comment by ImplementsLegend** [comment]
another known issue... btw what cpu is your server running on?

**Comment by FoxFireX** [comment]
CPU is Intel(R) Core(TM) i7-10700KF CPU @ 3.80GHz   3.79 GHz

Is there an earlier build I should switch to for the time being? Absolutely addicted to the performance boost from this.

**Comment by ImplementsLegend** [comment]
Are you running it in a VM with limited number of cores? I wasn't getting any deadlocks in previous public releases and neither did other people. Check out if the issue persists in the new version.

**Comment by FoxFireX** [comment]
No, it's running directly on the machine. It's my personal desktop, so it's also running a client at the same time, but I'm not artificially limiting the cores in any way that I know. I'll get the new one on there and let you know if anything else comes up. I'll also try to provide a list of other mods in case something is causing a conflict.

**Comment by ImplementsLegend** [comment]
I don't think it was caused by other mods, i was just looking for a reason why would it happen to you specifically and no-one else as far as i know

**Comment by FoxFireX** [comment]
Just passing along a note, haven't run into either of the issues described since installing the newer release. So far so good.
